### ISSUE TITLE
python2.7.18 UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by SpringTang2021** [SpringTang2021/test_project_pytest#1]
if this test project is under a working path with non-english names(such as chinese names， eg: D:\我的工作目录\dev_box\test)
   then you will got the following error when you directly run this project
 
Traceback (most recent call last):
  File "d:\program files (x86)\python2.7.18\lib\logging\__init__.py", line 868, in emit
    msg = self.format(record)
  File "d:\program files (x86)\python2.7.18\lib\logging\__init__.py", line 741, in format
    return fmt.format(record)
  File "d:\program files (x86)\python2.7.18\lib\logging\__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 29: ordinal not in range(128)
Logged from file conftest.py, line 22

**Comment by SpringTang2021** [comment]
the solution is:
1. touch a file named  sitecustomize.py under python2.7.18\Lib\site-packages
with the following content:
` # encoding=utf8  `
` import sys  `
` reload(sys)  `
` sys.setdefaultencoding('gbk')`

2. remove pycache dir under test project
 
3. relaunch python and execute pytest
